plugins:
  - '@trivago/prettier-plugin-sort-imports'
singleQuote: true
semi: true
printWidth: 100
trailingComma: none
importOrder:
  - '^[^@]'
  - '^@(?!commons|main|renderer|resources)(.*)$'
  - '^@commons/(.*)$'
  - '^@main/(.*)$'
  - '^@renderer/(.*)$'
  - '^@resources/(.*)$'
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
