name: Release AppImage

on:
  push:
    branches:
      - main

jobs:
  build_rogcontrolcenter:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-tools-dev qt6-tools-dev-tools build-essential cmake

      - name: Compile
        run: make build_rogcontrolcenter

      - name: Get version
        id: get_version
        run: |
          echo "version=$(uv run scripts/version.py)" >> $GITHUB_OUTPUT
