name: Release AppImage

on:
  push:
    branches:
      - main

jobs:
  build_rogcontrolcenter:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-tools-dev qt6-tools-dev-tools build-essential cmake libsecret-1-dev libzstd-dev pkg-config libudev-dev

      - name: Compile
        run: |
          cmake --version
          make build_rogcontrolcenter

      - name: Get version
        id: get_version
        run: |
          echo "version=$(cat assets/version)" >> $GITHUB_OUTPUT

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: build/RccCore/RogControlCenter

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: assets

  build_openrgb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2

      - name: Compile
        run: |
          make build_openrgb

      - name: Upload OpenRGB
        uses: actions/upload-artifact@v4
        with:
          name: OpenRGB
          path: assets/OpenRGB

  build_rccdc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          npm i -g pnpm@8.5.1 shx@0.3.4

      - name: Compile
        run: |
          make build_rccdc

      - name: Upload RccDeckyCompanion
        uses: actions/upload-artifact@v4
        with:
          name: OpenRGB
          path: assets/RccDeckyCompanion
