name: Release AppImage

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2
          npm i -g pnpm@8.5.1 shx@0.3.4
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep '^version *= *' pyproject.toml | sed 's/version *= *"\(.*\)"/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"

      - name: Run make release
        run: make release

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          files: dist/RogControlCenter.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Reset submodules
        run: |
          git submodule foreach --recursive "git reset --hard"
          git submodule foreach --recursive "git clean -fd"

      - name: Push changes to main and force push to develop
        run: |
          git push origin 
          git push origin main:develop --force
