name: Release AppImage

on:
  push:
    branches:
      - main

jobs:
  compile_and_package:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2 qt6-base-dev qt6-tools-dev qt6-tools-dev-tools build-essential cmake libsecret-1-dev libzstd-dev pkg-config libudev-dev clang-format
          npm i -g pnpm@8.5.1 shx@0.3.4

      - name: Format
        run: |
          make format
          if [[ -n $(git status --porcelain) ]]; then
              echo "Commiting formated files..."
              git add .
              git commit -m "[ci skip] Auto formatted source files"
              git push
          fi

      - name: Compile
        run: |
          cmake --version
          make release

      - name: Get version
        id: get_version
        run: |
          echo "version=$(cat assets/version)" >> $GITHUB_OUTPUT

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: dist/RogControlCenter.AppImage

  release:
    needs:
      - compile_and_package
      - package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure git client
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create tag
        run: |
          git pull --rebase origin main
          git tag "${{ needs.compile_and_package.outputs.version }}"
          make increase_version
          git push origin main
          git push origin main:develop --force
          git checkout develop
          git add CMakeLists.txt > /dev/null
          git commit -m "[ci skip] Ready for next development iteration" > /dev/null
          git push origin develop --force

      - name: Download AppImage artifact
        uses: actions/download-artifact@v4
        with:
          name: AppImage
          path: dist

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.compile.outputs.version }}
          name: ${{ needs.compile.outputs.version }}
          files: |
            dist/RogControlCenter.AppImage<
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
